jenkins:
  systemMessage: "Simple Multibranch Pipeline Job stored as code"
jobs:
  - >
      multibranchPipelineJob('jenkins-config-as-code-job') {
        branchSources {
          git {
            id('jenkins-casc-branchSource')
            remote('https://github.com/mdelgin/jenkins-config-as-code.git')
            includes('*')
          }
        }
      }
