jenkins:
  systemMessage: "Jenkins configured as code!"
unclassified:
  globalLibraries:
    libraries:
      - name: "cloudy-demos-shared-library"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/cloudy-demos/pipeline-libraries.git"
jobs:
  - >
      multibranchPipelineJob('jenkins-config-as-code-job') {
        branchSources {
          git {
            id('jenkins-casc-branchSource')
            remote('https://github.com/mdelgin/jenkins-config-as-code.git')
            includes('*')
          }
        }
      }
