jenkins:
  systemMessage: "Pipeline Job stored as code"
jobs:
  - >
      multibranchPipelineJob('jenkins-config-as-code-job') {
        branchSources {
          git {
            remote('https://github.com/mdelgin/jenkins-config-as-code.git')
          }
        }
      }
